apiVersion: v1
appVersion: 4.5.0
description: A Helm chart for the deployment of WSO2 API Manager all-in-one distribution.
icon: https://wso2.cachefly.net/wso2/sites/all/images/wso2logo.svg
name: wso2am-all-in-one
version: 4.5.0-1
