apiVersion: v2
appVersion: 1.3.0
dependencies:
- condition: certmanager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.17.1
description: A Helm chart for deploying apim-apk-agent
name: apim-apk-agent
type: application
version: 1.3.0
