apiVersion: v2
appVersion: 1.3.0-1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.14
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.10.0
- condition: certmanager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.17.1
description: A Helm chart for APK components
name: apk-helm
type: application
version: 1.3.0-1
